-- MySQL Script generated by MySQL Workbench
-- Seg 05 Dez 2016 19:41:50 BRST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema eadifmg
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eadifmg
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eadifmg` DEFAULT CHARACTER SET utf8 ;
USE `eadifmg` ;

-- -----------------------------------------------------
-- Table `eadifmg`.`ConselhoClasse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eadifmg`.`ConselhoClasse` (
  `id_conselho` INT NOT NULL AUTO_INCREMENT,
  `descricao_conselho` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_conselho`),
  UNIQUE INDEX `id_conselho_UNIQUE` (`id_conselho` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eadifmg`.`Questionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eadifmg`.`Questionario` (
  `id_questionario` INT NOT NULL AUTO_INCREMENT,
  `titulo_questionario` VARCHAR(50) NOT NULL,
  `descricao_questionario` VARCHAR(200) NOT NULL,
  `id_conselho` INT NOT NULL,
  PRIMARY KEY (`id_questionario`),
  UNIQUE INDEX `id_questionario_UNIQUE` (`id_questionario` ASC),
  INDEX `fk_Questionario_ConselhoClasse_idx` (`id_conselho` ASC),
  CONSTRAINT `fk_Questionario_ConselhoClasse`
    FOREIGN KEY (`id_conselho`)
    REFERENCES `eadifmg`.`ConselhoClasse` (`id_conselho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eadifmg`.`Questao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eadifmg`.`Questao` (
  `id_questao` INT NOT NULL AUTO_INCREMENT,
  `descricao_questao` VARCHAR(100) NOT NULL,
  `id_questionario` INT NOT NULL,
  PRIMARY KEY (`id_questao`),
  UNIQUE INDEX `id_questao_UNIQUE` (`id_questao` ASC),
  INDEX `fk_Questao_Questionario1_idx` (`id_questionario` ASC),
  CONSTRAINT `fk_Questao_Questionario1`
    FOREIGN KEY (`id_questionario`)
    REFERENCES `eadifmg`.`Questionario` (`id_questionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eadifmg`.`Resposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eadifmg`.`Resposta` (
  `id_resposta` INT NOT NULL AUTO_INCREMENT,
  `descricao_resposta` VARCHAR(100) NOT NULL,
  `id_questao` INT NOT NULL,
  PRIMARY KEY (`id_resposta`),
  UNIQUE INDEX `id_resposta_UNIQUE` (`id_resposta` ASC),
  INDEX `fk_Resposta_Questao1_idx` (`id_questao` ASC),
  CONSTRAINT `fk_Resposta_Questao1`
    FOREIGN KEY (`id_questao`)
    REFERENCES `eadifmg`.`Questao` (`id_questao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Table `eadifmg`.`ConselhoClasse`. CARGA INICIAL
-- -----------------------------------------------------
INSERT INTO ConselhoClasse (descricao_conselho) values ('Primeira reunião do Conselho de Classe.');
INSERT INTO ConselhoClasse (descricao_conselho) values ('Segunda reunião do Conselho de Classe.');
INSERT INTO ConselhoClasse (descricao_conselho) values ('Terceira reunião do Conselho de Classe.');
