<h1>Trabalho Final</h1>
<br />
Bem-vindo ao sistema de gerenciamento de Questionários e Questões.
<br /><br /><br />
Observações:<br />
1) Projeto baseado no tutorial oficial: "slimframework.com/docs/tutorial/first-app.html".
<br />
2) Consulte o modelo do banco de dados: "model-data.png".
<br />
3) Execute os scripts do banco de dados: "script-data.sql".
<br />
4) Altere as configurações da aplicação: "controllers/config.php".