<h1>Editar Questionário</h1>
<?php foreach ($questionarios as $questionario): ?>
<form action="/conselho-classe/<?=$questionario['id_conselho'] ?>/questionario/<?=$questionario['id_questionario'] ?>/salvar" method="post">
<table class="table">
    <tr>
        <th>ID</th>
        <th>Informações</th>
        <th>Ação</th>
    </tr>
    <tr>
        <td class="id">
            <?=$questionario['id_questionario'] ?>
        </td>
        <td class="titulo">
            <div>
                <label for="titulo">Título:</label>
                <input type="text" id="titulo_questionario"  maxlength="50" name="titulo_questionario" value="<?=$questionario['titulo_questionario'] ?>">
            </div>
            <div>
                <br />
                <label for="descricao">Descrição:</label>
                <textarea id="descricao_questionario" maxlength="200" name="descricao_questionario"><?=$questionario['descricao_questionario'] ?></textarea>
            </div>
        </td>
        <td class="id">
            <div class="button">
                 <input type="hidden" name="id_questionario" value="<?=$questionario['id_questionario'] ?>">
                 <input type="hidden" name="id_conselho" value="<?=$questionario['id_conselho'] ?>">
                 <button type="submit" id="salvar_questionario">Salvar</button>
                 <br /><br />
                 <button type="button" id="voltar">Voltar</button>
            </div>
        </td>
    </tr>
</table>
</form>
<?php endforeach; ?>