<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">

        <link rel="stylesheet" type="text/css" href="/public/css/estilo.css">
        <script src="/public/js/jquery-3.1.1.min.js"></script>
        <script src="/public/js/functions.js"></script>

        <title>Trabalho Final</title>
    </head>

    <body>
        <div class="principal">
            <div class="cabecalho">
                <div class="logo-cabecalho"></div>
            </div>
            <div class="menu">
                <ul>
                    <li> <a href="/">Início</a></li>
                    <li> <a href="/conselho-classe">Conselho de Classe</a></li>
                </ul>
            </div>
            <div class="corpo">
                <div class="conteudo">